name: Publish server jar to GitHub Packages

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Make gradlew executable
        working-directory: ./wibb-ws-j
        run: chmod +x ./gradlew
      - name: Publish package
        working-directory: ./wibb-ws-j
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            ./wibb-ws-j/build/libs/*.jar
