name: Publish server jar to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Make gradlew executable
        working-directory: ./wibb-ws-j
        run: chmod +x ./gradlew
      - name: Running checks
        working-directory: ./wibb-ws-j
        run: ./gradlew check --stacktrace
      - name: Calculating new version
        id: new_version_string
        working-directory: ./wibb-ws-j
        run: WIBB_VERSION=`./gradlew printVersion | grep wibb-v\d*\.\d*\.\d*-\d*`
      - name: Tag snapshot
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ WIBB_VERSION }}
      - name: Publish package
        working-directory: ./wibb-ws-j
        run: ./gradlew publish --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            ./wibb-ws-j/build/libs/*.jar
