name: Publish server jar to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Make gradlew executable
        working-directory: ./wibb-ws-j
        run: chmod +x ./gradlew
      - name: Running checks
        working-directory: ./wibb-ws-j
        run: ./gradlew check --stacktrace
      - name: Creating git version tag
        working-directory: ./wibb-ws-j
        run: ./gradlew printVersion | grep wibb-v\d*\.\d*\.\d*-\d* | xargs git tag
      - name: Pushing tags
        working-directory: ./wibb-ws-jar
        run: git push --tags
      - name: Publish package
        working-directory: ./wibb-ws-j
        run: ./gradlew publish --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            ./wibb-ws-j/build/libs/*.jar
